version: "3.8"
services:

  backend-go:
    build:
      context: ..
      dockerfile: development/backend-go/dev.dockerfile
    environment:
      MYSQL_HOST: mysql-backend
      MYSQL_PORT: 3306
      MYSQL_DATABASE: isucondition
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
      ISU_CONDITION_IP: backend-go
    entrypoint: dockerize -wait tcp://mysql-backend:3306 -timeout 60s
    command: air -c /development/air.toml
    ports:
      - "3000:3000"
    volumes:
      - "../webapp/go:/webapp/go"
      - "../webapp/mysql:/webapp/mysql"
      - "../webapp/ec256-public.pem:/webapp/ec256-public.pem"
      - "../webapp/NoImage.png:/webapp/NoImage.png"
    depends_on:
      - mysql-backend
  # MEMO: 各言語用のコンテナをここ以下に列挙
  # backend-python:
  # ...

  mysql-backend:
    image: mariadb:10.6.2-focal
    restart: always
    environment:
      MYSQL_DATABASE: isucondition
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "../development/mysql-backend/mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
      # 開発環境用のものを使って初期化
      - "../webapp/mysql/db/0_Schema.sql:/docker-entrypoint-initdb.d/0_Schema.sql"
      - "../development/mysql-backend/1_Constraint.sql:/docker-entrypoint-initdb.d/1_Constraint.sql"
      - "../development/mysql-backend/2_Init.sql:/docker-entrypoint-initdb.d/2_Init.sql"
    expose:
      - "3306"
    ports:
      - "3306:3306"

  jiaapi-sa:
    image: golang:1.16.5-buster
    restart: always
    working_dir: /jiaapi
    command: ["go", "run", "./cmd/standalone/"]
    environment:
      JWT_SECRETKEY_PATH: /bench/key/ec256-private.pem
    ports:
      - "5000:5000"
    volumes:
      - "../extra/jiaapi:/jiaapi"
      - "../bench:/bench"
