version: "3.8"
services:
  backend-go:
    build:
      context: ..
      dockerfile: development/backend-go/Dockerfile
    environment:
      MYSQL_HOST: mysql-backend
      MYSQL_PORT: 3306
      MYSQL_DATABASE: isucondition
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
    entrypoint: dockerize -wait tcp://mysql-backend:3306 -timeout 60s
    command: air -c /development/air.toml
    ports:
      - "3000:3000"
    volumes:
      - "../webapp/go:/go/src/isucondition"
    depends_on:
      - mysql-backend

  mysql-backend:
    image: mysql:8.0.25
    restart: always
    environment:
      MYSQL_DATABASE: isucondition
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
      MYSQL_ROOT_PASSWORD: root
    expose:
      - "3306"
    ports:
      - "3306:3306"

  apitest:
    build:
      context: ..
      dockerfile: development/apitest/Dockerfile
    environment:
      TARGET_ADDRESS: $target
    depends_on:
      - mysql-backend
