version: "3.8"
services:
  backend:
    build:
      context: ..
      dockerfile: development/backend-${target}/ci.dockerfile
    environment:
      MYSQL_HOST: mysql-backend
      MYSQL_PORT: 3306
      MYSQL_DATABASE: isucondition
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
    ports:
      - "3000:3000"
    volumes:
      - "../webapp/ec256-public.pem:/webapp/ec256-public.pem"
    depends_on:
      - mysql-backend

  mysql-backend:
    image: mysql:8.0.25
    restart: always
    environment:
      MYSQL_DATABASE: isucondition
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
      MYSQL_ROOT_PASSWORD: root
    expose:
      - "3306"
    ports:
      - "3306:3306"

  apitest:
    build:
      context: ..
      dockerfile: development/apitest/ci.dockerfile
    environment:
      TARGET_ADDRESS: backend
    entrypoint: dockerize -wait http://backend:3000 -timeout 60s
    depends_on:
      - mysql-backend
      - backend
