---
- name: "roles/contestant/tasks/isucondition: Deploy isucon11-qualify"
  become_user: isucon
  copy:
    remote_src: yes
    src: /tmp/isucon11-qualify/webapp
    dest: /home/isucon/
    owner: isucon
    group: isucon

- name: "roles/contestant/tasks/isucondition: Include generate_env.yml"
  include: generate_env.yml

- name: "roles/contestant/tasks/isucondition: Include isucondition-frontend.yml"
  include: isucondition-frontend.yml

- name: "roles/contestant/tasks/isucondition: Include isucondition-go.yml"
  include: isucondition-go.yml

# TODO: 言語別の include

- name: "roles/contestant/tasks/isucondition: Enable isucondition.go.service"
  become_user: root
  systemd:
    daemon_reload: "yes"
    name: "isucondition.go.service"
    state: "restarted"
    enabled: "yes"

- name: "roles.contestant.tasks.isucondition: Deploy isucon11 initial-data"
  copy:
    src: "initial-data.sql"
    dest: "/tmp/initial-data.sql"

- name: "roles.contestant.tasks.isucondition: Initialize isucondition Database"
  become_user: isucon
  shell: |
    mysql -uisucon -pisucon < /tmp/initial-data.sql
    # TODO
    #curl -X POST http://localhost/initialize -f

- name: "roles.contestant.tasks.isucondition: Remove isucon11 initial-data"
  file:
    path: /tmp/initial-data.sql
    state: absent
