---
- name: "roles/contestant/tasks/isucondition: Deploy isucon11-qualify"
  become_user: isucon
  copy:
    remote_src: yes
    src: /tmp/isucon11-qualify/webapp
    dest: /home/isucon/
    owner: isucon
    group: isucon

- name: "roles/contestant/tasks/isucondition: Deploy configs"
  become_user: isucon
  copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: isucon
    group: isucon
  with_items:
    - home/isucon/env.sh
    - etc/hosts


- name: "roles/contestant/tasks/isucondition: Include isucondition-frontend.yml"
  include: isucondition-frontend.yml

- name: "roles/contestant/tasks/isucondition: Include isucondition-go.yml"
  include: isucondition-go.yml

# TODO: 言語別の include

- name: "roles/contestant/tasks/isucondition: Enable isucondition.go.service"
  become_user: root
  systemd:
    daemon_reload: "yes"
    name: "isucondition.go.service"
    enabled: "yes"

- name: "roles/contestant/tasks/isucondition: Deploy isucon11 initial-data"
  copy:
    src: "initial-data.sql"
    dest: "/home/isucon/webapp/sql/1_InitData.sql"
    owner: isucon
    group: isucon
    mode: "0644"

- name: "roles/contestant/tasks/isucondition: Initialize isucondition database"
  become_user: isucon
  shell: |
    mysql -uisucon -pisucon -e 'CREATE DATABASE isucondition'
    bash /home/isucon/webapp/sql/init.sh
