---
- name: "roles/contestant/tasks/isucondition-ruby: Build Web Application ruby"
  become_user: isucon
  args:
    chdir: /home/isucon/webapp/ruby
  environment:
    PATH: "/home/isucon/local/ruby/bin:{{ ansible_env.PATH }}"
  shell: |
    bundle config set deployment true && \
    bundle config set path /gems && \
    bundle config set without 'development test' && \
    bundle install -j4
