---
- name: "roles.contestant.tasks.langs-go: Install Go 1.16.5 from xbuild"
  command: /tmp/xbuild/go-install 1.16.5 /home/isucon/local/go

- name: "roles.contestant.tasks.langs-go: - name: Add PATH for Go"
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK go"
    path: /home/isucon/.bashrc
    content: |
      export PATH=/home/isucon/local/go/bin:/home/isucon/go/bin:$PATH
      export GOROOT=/home/isucon/local/go

