---

# TODO: s/isucon10/isucon11/g
- name: "roles/bench.supervisor/tasks/main: Clone isucon/isucon11-portal"
  become: no
  git:
    repo: git@github.com:isucon/isucon10-portal
    dest: /tmp/isucon11-portal

- name: "roles/bench.supervisor/tasks/main: Build isuxportal-supervisor"
  become_user: isucon
  args:
    chdir: /tmp/isucon11-portal/supervisor
  shell: cargo build --release --bin isuxportal-supervisor

- name: "roles/bench.supervisor/tasks/main: Deploy isuxportal-supervisor"
  copy:
    remote_src: yes
    src: /tmp/isucon11-portal/supervisor/target/release/isuxportal-supervisor
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: "0755"

- name: "roles/bench.supervisor/tasks/main: Deploy some files"
  become_user: root
  copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - etc/systemd/system/isuxportal-supervisor.service
    - run/isuxportal-supervisor.env

- name: "roles/bench.supervisor/tasks/main: Enable isuxportal-supervisor.service"
  become_user: root
  systemd:
    daemon_reload: "yes"
    name: "isuxportal-supervisor.service"
    enabled: "yes"
