---
- name: bench
  become: true
  hosts: [all]
  tags:
    - bench
    - full
  roles:
    - common
    - bench

- name: contestant
  become: true
  hosts: [all]
  tags:
    - contestant
    - full
  roles:
    - common
    - contestant
