---
- name: all
  become: true
  hosts: [all]
  tags:
    - contestant
    - bench
    - standalone
  roles:
    - common
    - langs

- name: contestant
  become: true
  hosts: [all]
  tags:
    - contestant
    - standalone
  roles:
    - langs.go
    - langs.nodejs
    - contestant

- name: bench
  become: true
  hosts: [all]
  tags:
    - bench
  roles:
    - langs.go
    - langs.rust
    - bench
    - bench.supervisor

- name: bench-standalone
  become: true
  hosts: [all]
  tags:
    - standalone
  roles:
    - bench

