---
- name: "roles/bench/tasks/bench: Run assets gen"
  environment:
    PATH: "/home/isucon/local/go/bin:{{ ansible_env.PATH }}"
  shell: go generate /tmp/isucon11-qualify/bench/gen/assets.go

- name: "roles/bench/tasks/bench: Deploy isucon11-qualify bench"
  become_user: isucon
  copy:
    remote_src: yes
    src: /tmp/isucon11-qualify/bench
    dest: /home/isucon/
    owner: isucon
    group: isucon

- name: "roles/bench/tasks/bench: Deploy certificates for bench (jiaapi.t.isucon.dev)"
  become_user: isucon
  copy:
    src: "{{ item }}"
    dest: "/home/isucon/bench/{{ item }}"
    owner: isucon
    group: isucon
  with_items:
    - tls-cert.pem
    - tls-key.pem

- name: "roles/bench/tasks/bench: Deploy initial-data for bench"
  become_user: isucon
  copy:
    src: "initialize.json"
    dest: /home/isucon/bench/data/
    owner: isucon
    group: isucon

- name: "roles/bench/tasks/bench: Build Web Application Go"
  become_user: isucon
  args:
    chdir: /home/isucon/bench
  environment:
    PATH: "/home/isucon/local/go/bin:{{ ansible_env.PATH }}"
  shell: |
    go build -o bench .
