name: frontend

on:
  push:
    branches: [ main ]
    paths:
      - webapp/frontend/**/*
      - .github/workflows/frontend.yml
  pull_request:
    paths:
      - webapp/frontend/**/*
      - .github/workflows/frontend.yml

jobs:
  packages:
    name: Packages
    runs-on: ubuntu-latest
    env:
      CI: true
    defaults:
      run:
        working-directory: webapp/frontend
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/checkout@v2
      - run: npm ci
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [packages]
    env:
      CI: true
    defaults:
      run:
        working-directory: webapp/frontend
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [packages]
    env:
      CI: true
    defaults:
      run:
        working-directory: webapp/frontend
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run fmt:check
      - run: npm run lint
